name: Publish

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2019]
      fail-fast: false

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install build tools
        if: startsWith(matrix.os, 'windows')
        run: ./scripts/ci/install-vs-build-tools.ps1 -IncludeWin81Sdk $true
        shell: powershell

      - name: Set msvs_version
        if: startsWith(matrix.os, 'windows')
        run: |
          npm config set msvs_version "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"
          npm config set msbuild_path "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe"
          dir "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"

      - name: Install node-gyp
        if: startsWith(matrix.os, 'windows')
        run: ./scripts/ci/install-node-gyp.ps1
        shell: powershell

      - name: envinfo
        run: npx envinfo

      - name: Prepare for app notarization
        if: startsWith(matrix.os, 'macos')
        run: |
          mkdir -p ~/private_keys/
          echo '${{ secrets.api_key }}' > ~/private_keys/AuthKey_${{ secrets.api_key_id }}.p8

      - name: Build/Release
        uses: samuelmeuli/action-electron-builder@v1
        with:
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}
          windows_certs: ${{ secrets.windows_certs }}
          windows_certs_password: ${{ secrets.windows_certs_password }}
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          max_attempts: 2
        env:
          APPLE_ID: ${{ secrets.apple_id }}
          APPLE_ID_PASSWORD: ${{ secrets.apple_id_pwd }}
          APPLE_TEAM_ID: ${{ secrets.apple_team_id }}
          GH_TOKEN: ${{ secrets.gh_token }}
